In [9]:
import numpy as np
import pandas as pd

csv = r"Electric_Vehicle_Population_Data.csv"

def load_and_process(csv_file):
    
    df1 = (
        pd.read_csv(csv_file)
        .drop('State', axis=1)
        .drop('Clean Alternative Fuel Vehicle (CAFV) Eligibility', axis=1)
        .drop('Legislative District', axis=1)
        .drop('DOL Vehicle ID', axis=1)
        .rename(columns={'VIN (1-10)': 'VIN'})
        .rename(columns={'ZIP Code': 'ZIP'})
        .rename(columns={'Model Year': 'Model_Year'})
        .rename(columns={'Electric Vehicle Type': 'EV_Type'})
        .rename(columns={'Electric Range': 'Range'})
        .rename(columns={'Base MSRP': 'MSRP'})
        .rename(columns={'Vehicle Location': 'Location'})
        .dropna()
        .reset_index(drop=True)
    )
    
    df1.loc[df1.EV_Type == 'Plug-in Hybrid Electric Vehicle (PHEV)', 'EV_Type'] = 'PHEV'
    df1.loc[df1.EV_Type == 'Battery Electric Vehicle (BEV)', 'EV_Type'] = 'BEV'
    
    df1['Latitude'] = df1.apply(lambda row: float(row.Location.split(" ")[2].split(")")[0]), axis = 1)
    df1['Longitude'] = df1.apply(lambda row: float(row.Location.split(" ")[1].split("(")[1]), axis = 1)
    df1['North_South'] = np.where(df1['Latitude']>=47.2, 'North', 'South')
    df1['West_East'] = np.where(df1['Longitude']>=120, 'West', 'East')
    return df1

load_and_process(csv)

,VIN,County,City,ZIP,Model_Year,Make,Model,EV_Type,Range,MSRP,Location,Latitude,Longitude,North_South,West_East
0,JA4J24A5XJ,King,KENT,98032,2018,MITSUBISHI,OUTLANDER,PHEV,22,34595,POINT (-122.26132099999998 47.390601),47.390601,-122.261321,North,East
1,JN1AZ0CP7B,King,COVINGTON,98042,2011,NISSAN,LEAF,BEV,73,32780,POINT (-122.11667400000002 47.363112),47.363112,-122.116674,North,East
2,1G1FW6S07H,Clark,CAMAS,98607,2017,CHEVROLET,BOLT,BEV,238,37495,POINT (-122.40849800000001 45.620943),45.620943,-122.408498,South,East
3,1N4AZ0CP6D,King,SEATTLE,98117,2013,NISSAN,LEAF,BEV,75,28800,POINT (-122.379354 47.687571),47.687571,-122.379354,North,East
4,JN1AZ0CP1B,Clark,CAMAS,98607,2011,NISSAN,LEAF,BEV,73,32780,POINT (-122.40849800000001 45.620943),45.620943,-122.408498,South,East
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60920,5YJ3E1EC7L,King,SEATTLE,98119,2020,TESLA,MODEL 3,BEV,308,0,POINT (-122.36772100000002 47.639264),47.639264,-122.367721,North,East
60921,KNAGU4LE4K,Pierce,BONNEY LAKE,98391,2019,KIA,OPTIMA PLUG-IN HYBRID,PHEV,29,35390,POINT (-122.170798 47.184615),47.184615,-122.170798,South,East
60922,1G1RA6E42C,San Juan,EASTSOUND,98245,2012,CHEVROLET,VOLT,PHEV,35,39145,POINT (-122.924946 48.657249),48.657249,-122.924946,North,East
60923,WBY8P6C05L,King,SEATTLE,98122,2020,BMW,I3,BEV,153,0,POINT (-122.303413 47.61065),47.610650,-122.303413,North,East
60924,JN1AZ0CP6B,Snohomish,EVERETT,98208,2011,NISSAN,LEAF,BEV,73,32780,POINT (-122.19615 47.894423),47.894423,-122.196150,North,East